# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc3169a193245ebf47562c7dd8104195430f4d805ce3e23b71883689297640b73572de5398f9e4fdf87ddfdf66b3e2dc920e40b6f125d0b7c7e0c134f9334c37

test:
  secret_key_base: 3238443eae7d19d91809323852bade0ce9037077869d63c55829fc52703ff302bae9e3b29ca2f79007a32776fd4b6c5709bab02d3f38068bd94bff29c33f08e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
